name: CI

on:
  # Trigger the workflow on push or pull requests, but only for the
  # main branch
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  msbuild:
    runs-on: 'windows-latest'
    steps:
    - name: Checkout open-sysmon-conf
      uses: actions/checkout@v2
      
    - name: Run Sysmon 
      run: \\live.sysinternals.com\tools\sysmon.exe -accepteula -i sysmonconfig-export.xml
      shell: powershell
      
